"""create deployment, agent_finding, and outcome tables

Revision ID: 4d9094497aa5
Revises: 9eee17c73084
Create Date: 2026-08-27 20:33:43.474737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9094497aa5'
down_revision: Union[str, Sequence[str], None] = '9eee17c73084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
