"""create deployment, agent_finding, and outcome tables

Revision ID: 9eee17c73084
Revises: 
Create Date: 2026-08-27 19:24:09.835226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eee17c73084'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('uuid_val', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid_val')
    )
    op.create_table('agent_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid_val', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.Enum('CODE_REVIEW', 'DEPENDENCY_SECURITY', 'CICD_ANALYZER', 'LOGS', name='agenttype'), nullable=False),
    sa.Column('find_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid_val')
    )
    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid_val', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.String(length=50), nullable=False),
    sa.Column('suggested_fix', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'APPLIED', 'VALIDATED', 'REJECTED', name='outcomestatus'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid_val')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcomes')
    op.drop_table('agent_findings')
    op.drop_table('deployments')
    # ### end Alembic commands ###
